/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellArchitectedRouteImport } from './routes/well-architected'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as RplRouteImport } from './routes/rpl'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const WellArchitectedRoute = WellArchitectedRouteImport.update({
  id: '/well-architected',
  path: '/well-architected',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RplRoute = RplRouteImport.update({
  id: '/rpl',
  path: '/rpl',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/observability': typeof ObservabilityRoute
  '/rpl': typeof RplRoute
  '/scenarios': typeof ScenariosRoute
  '/well-architected': typeof WellArchitectedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/observability': typeof ObservabilityRoute
  '/rpl': typeof RplRoute
  '/scenarios': typeof ScenariosRoute
  '/well-architected': typeof WellArchitectedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/observability': typeof ObservabilityRoute
  '/rpl': typeof RplRoute
  '/scenarios': typeof ScenariosRoute
  '/well-architected': typeof WellArchitectedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/observability'
    | '/rpl'
    | '/scenarios'
    | '/well-architected'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/observability'
    | '/rpl'
    | '/scenarios'
    | '/well-architected'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/observability'
    | '/rpl'
    | '/scenarios'
    | '/well-architected'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ObservabilityRoute: typeof ObservabilityRoute
  RplRoute: typeof RplRoute
  ScenariosRoute: typeof ScenariosRoute
  WellArchitectedRoute: typeof WellArchitectedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/well-architected': {
      id: '/well-architected'
      path: '/well-architected'
      fullPath: '/well-architected'
      preLoaderRoute: typeof WellArchitectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpl': {
      id: '/rpl'
      path: '/rpl'
      fullPath: '/rpl'
      preLoaderRoute: typeof RplRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ObservabilityRoute: ObservabilityRoute,
  RplRoute: RplRoute,
  ScenariosRoute: ScenariosRoute,
  WellArchitectedRoute: WellArchitectedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
